---

- hosts: dnf-servers
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache: yes
      state: latest

  - name: install apache2 package
    dnf:
      name: httpd

  - name: add php support for apache
    dnf:
      name: libapache2-mod-php
      state: latest




