---

- hosts: all
  become: yes
  become_method: sudo
  pre_tasks:

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates (RedHat)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RED"


- hosts: web-servers
  become: yes
  become_method: sudo
  tasks:
    - name: install apache and PHP for Ubuntu servers
      apt:
        name:
          - apache2
          - libapache2-mod-php


- hosts: db-servers
  become: yes
  become_method: sudo
  tasks:

  - name: install mariadb package (Ubuntu)
    apt:
      name: 
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file-servers
  become: yes
  become_method: sudo
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest

