---

- hosts: all
  become: true
  become_method: sudo
  pre_tasks:

    - name: Install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install updates (RedHat)
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "RED"

- hosts: all
  become: true
  become_method: sudo
  tasks:

    - name: Create ansible-test user
      user:
        name: ansible-test
        groups: "root"

    - name: Add SSH key for ansible-test user
      authorized_key:
        user: ansible-test
        key: ""

    - name: Add ansible-test user to sudoers
      copy:
        dest: "/etc/sudoers.d/ansible-test"
        content: "ansible-test ALL=(ALL) NOPASSWD: ALL"
        mode: '440'

